### ISSUE TITLE
Draw in both layers

### ISSUE THREAD

**Issue by danilolc** [Detea/PekaED#25]
When the both layer view is enable, the editor draws in both layers. This could be a problem when drawing key blocks for example.

**Comment by Detea** [comment]
That is how the "both" layer is supposed to work.
The user can select the fore-/background layer to draw on them.

Functionality of the "both" layer is documented in the [official manual](https://detea.github.io/pekaed/#Layers).

**Comment by danilolc** [comment]
But sometimes I need to draw to the foreign layer viewing the foreign layer, also in the official editor the both layer draw only on the foreign layer. When I had drawn the key blocks I saw that they wasn't disappearing, then I noticed that there was key blocks on background too. What I suggest is show both layer every time, but the not drawn layer will be more gray, or transparent.

**Comment by Detea** [comment]
If you want to draw on and see the foreground layer you can choose it. If you want to the see fore and background layer, but see both at the same time, that's not possible. Although, it's an interesting idea to draw both layers, but only show the inactive one at like half transparency, or brightness, or whatever.

I'll test it out.
