### ISSUE TITLE
PekaED can't load about 30% of the maps

### ISSUE THREAD

**Issue by Minhoquinha** [Detea/PekaED#26]
A lot of the levels that i try to load using the PekaED are not opened, when i press "open level" the editor lags for a second(still normal) but then nothing happens: It just stays at its original state. **I listed the levels that didn't work:**

Vanilla:
>Rooster Island 1:
 -Level 6
>Rooster Island 2:
 -Level 1 loaded, but was all [messed up](https://imgur.com/a/3cmez)
 -Level 4
 -Level 7
 -Level 8
 -Level 11 loaded and looked like level 12, but was all [messed up](https://imgur.com/a/3cmez)
 -Level 12 seems to have switched places with level 11, like it is level 11 loaded properly(or i am going crazy)
 -Level 13

Non vanilla(the ones i have in my computer at least):
>Forerunner's Island(episode made by me), episode with 13 levels:
 -Level 1
 -Level 2 loaded, but... MESSED UP(just use the same link above)
 -Level 4
 -Level 5
 -Level 6
 -Level 7
 -Level 8
 -Level 9
 -Level 11
 -Level 12
>[Isla Del Luna(episode made by Mipha)](http://pistegamez.proboards.com/thread/872/custom-episode-isla-del-luna), episode with 13 levels:
 -Level 1 seems to have switched places with other level, but was loaded properly
 -Level 2
 -Level 6 loaded, but it was messed up.
 -Level 9 seems to have switched places with level 1, but was loaded properly
 -Level 11 was the same as level 10.
>[Roosterfield(episode made by RowlandGardner)](http://pistegamez.proboards.com/thread/851/roosterfield-out), episode with 20 levels:
 -Level 2
 -Level 3
 -Level 6
 **-Level 8...
 -My PekaED bugged, windows and buttons are all at the top of each other, printscreen together with the prints of the messed up maps.
 -Stopped not only because PekaED bugged, but also because i don't want to see the spoilers from this episode, i already saw the spoilers from Isla Del Luna and i won't commit the same mistake.**
 

 I hope i have helped you, have a nice day. :)

**Comment by Detea** [comment]
Thank you, this is a very good bug report.

I have known about some levels from the second episode not loading correctly, or at all. I didn't prioritize fixing it, because pretty much all other levels I have tested worked fine. I probably shoud've done some more testing!

Edit: Also this was very naive of me, you shoul never just write off a bug. Lesson learned.

Now, seeing that all these levels listed above don't work, this is definitely an issue that'll be fixed in the next version.

**Comment by Detea** [comment]
All these levels _should_ load fine now. These problems where, because Isla Del Luna uses 1.2 sprites, which the editor didn't support, but now does and the levels from rooster island 2 are bigger than they should be. Although, they run fine in the game...

**Comment by Minhoquinha** [comment]
Oh really thanks! Can you please send the link of the updated version then?

**Comment by Detea** [comment]
[Here](https://www.dropbox.com/s/owmgjs6dumamibu/PekaED_v1.1_1.exe?dl=0) it is. If you want to test your levels you'll need the newst version of danilolcs port, which you can find [here.](https://files.fm/f/km8888gg)
