### ISSUE TITLE
"Calibrate" the mini map's zoom to the main screen

### ISSUE THREAD

**Issue by Minhoquinha** [Detea/PekaED#30]
If you try using the mini map white "square"(i know it is not a square) to see the bottom part of yout map, you will never be able to see the really bottom of it, because the format of the "zoom" in the mini map is not the same as the one of the main screen. Plus, mini map has an offset at the bottom that gives an impression that there is more space in the map than it really do.

**Comment by Detea** [comment]
Yeah, the extra space isn't supposed to be there. The mini map also isn't supposed to be in it's own window, unless it's fine like that. I wanted it to snap somewhere under the tiles panel, but that's a bit problematic when the editor is used on lower resolutions. This is an ongoing issue. The other problem is fixed.

**Comment by Detea** [comment]
The mini map is now integrated in the UI, this problem is fixed.
