### ISSUE TITLE
Add option to zoom in and zoom out the main screen

### ISSUE THREAD

**Issue by Minhoquinha** [Detea/PekaED#32]
I know the mini map already exists to the user be able to travel trought the map easier and see the whole map while seeing the main screen, but zoom out is good to the user be able to draw a bigger area without scrolling the screen(and zoom in is good to more accurate drawning). This problem was already present in regular editor and since PekkaED's screen is smaller, this problem is even more problematic.

**Comment by Detea** [comment]
Zooming out will definitely help users with lower resolutions and zooming in has to be implemented anyway, so this will be added.
