### ISSUE TITLE
New Icon for executable

### ISSUE THREAD

**Issue by Detea** [Detea/PekaED#4]
The editor needs a new and better icon for the exe, the current one doesn't look good and is pretty much just a placeholder.

**Comment by Minhoquinha** [comment]
Here an icon i made that may be good(or not): 
![icone pekkaed](https://user-images.githubusercontent.com/33009589/32137737-671ef0e4-bc04-11e7-9b36-900fe6dc7f27.PNG)

**Comment by Detea** [comment]
I have created a new icon, this issue will be closed.
