### ISSUE TITLE
Add support for night themed levels

### ISSUE THREAD

**Issue by Detea** [Detea/PekaED#7]
Currently all the levels produced with the editor have all the same light level, whatever the background is. However, some backgrounds change the light level. 

Note: Is this actually an issue? Have to test.

**Comment by RavMahov** [comment]
It's palette-related stuff. You need to use common palette for background and everything else. I can probably help with that.

**Comment by Detea** [comment]
That'd be great. I don't know how it works, I just know that it doesn't at the moment.
Edit: The editor just needs to know, which background has which night level, I guess? Would it be possible to set the night level manually, through the editor?

**Comment by Detea** [comment]
After some research and some testing I've come to the conclusion that the light level is not stored in the level file, so this bug doesn't actually exist. Although, there is still a field ("background") in the level format that I don't know the function of.

**Comment by RavMahov** [comment]
http://pistegamez.proboards.com/thread/729/understanding-pk2-palette-1

**Comment by Detea** [comment]
That was indeed a helpful resource. If you'd like you can create a page on the [wiki](https://github.com/Detea/PekaED/wiki) about how the palette works. I want to create a technical documentation of the game, so that anyone interested in doing something with it can just use the wiki.
